<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="C40BF52AGJUNC" name="com.qa.tester.sikuli_garcia" tests="1" failures="0" timestamp="04 Feb 2019 10:12:30 GMT" time="4.685" errors="1">
  <testcase name="tests" time="4.685" classname="com.qa.tester.sikuli_garcia">
    <error type="org.sikuli.script.FindFailed" message="can not find P(C:/Users/Suvneet.Singh/Desktop/sikuli_ss/drop.PNG) S: 0.7 in S(0)[0,0 1440x900]">
      <![CDATA[FindFailed: can not find P(C:/Users/Suvneet.Singh/Desktop/sikuli_ss/drop.PNG) S: 0.7 in S(0)[0,0 1440x900]
  Line 2189, in file Region.java

at org.sikuli.script.Region.handleFindFailedShowDialog(Region.java:2189)
at org.sikuli.script.Region.handleFindFailed(Region.java:2134)
at org.sikuli.script.Region.wait(Region.java:2546)
at com.qa.tester.sikuli_garcia.tests(sikuli_garcia.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tests -->
</testsuite> <!-- com.qa.tester.sikuli_garcia -->
